apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3-liq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v3-liq
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: v3-liq
    spec:
      containers:
        - name: v3-liq
          image: mango.azurecr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1250m
              memory: 6Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: NODE_OPTIONS
              value: --max_old_space_size=4096
            - name: CLUSTER
              value: mainnet
            - name: GROUP
              value: mainnet.1
            - name: INTERVAL
              value: "3000"
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: v3-liq-aks
                  key: private-key
            - name: ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: v3-liq-aks
                  key: endpoint-url
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: v3-liq-aks
                  key: webhook-url